### ISSUE TITLE
Can't click UI Tracker iconified icon

### ISSUE THREAD

**Issue by shuvashish76** [MuntashirAkon/AppManager#1179]
### Please check before submitting an issue

- [X] I know what my device, OS and App Manager versions are
- [X] I know how to take logs
- [ ] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

After UI Tracker window iconified drag it somewhere, now click the icon to reopen window option works 1 out of 5/6 times (random).

### Device info

- Device: moto g71 5G
- OS Version: 12
- App Manager Version: AM Debug v4.0.0-alpha01 Run#2570
- Mode: Root

### Additional context

No such issues on my Android 9 device.

**Comment by MuntashirAkon** [comment]
Can you try the latest debug?

**Comment by shuvashish76** [comment]
I don't have access to this specific device right now. Also after I changed the ROM I didn't experience this issue on the same device. So I can't test on this device anymore. Probably something specific to moto's stock ROM.
The another device I'm using has no such issues.
I'll reopen if I face similar issues on moto or my other devices.

**Comment by MuntashirAkon** [comment]
Related issue: #1207
