### ISSUE TITLE
Not Work UI Tracker

### ISSUE THREAD

**Issue by Vladik01-11** [MuntashirAkon/AppManager#1207]
### Please check before submitting an issue

- [X] I know what my device, OS and App Manager versions are
- [X] I know how to take logs
- [ ] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

When I activate UI Tracker, the entire App Manager application stops interacting in any way, that is, it is active, but nothing happens either.
I managed to launch UI Tracker once when I changed the language, but I think it's a coincidence and no more.

### To Reproduce

- 1. Open Labs.
- 2. Run UI Tracker.
- 2.1 Allow accessibility features.

### Expected behavior

Stable operation of UI Tracker

### Screenshots

![screen-recorder-unlimited-2023-10-01-01-24-02](https://github.com/MuntashirAkon/AppManager/assets/70571714/6b910197-8cc3-4eae-8b40-2abdea38b529)

### Logs

[2023-10-01-01-24-56.am.log](https://github.com/MuntashirAkon/AppManager/files/12775655/2023-10-01-01-24-56.am.log)

### Device info

- Device: Redmi 9T 
- OS Version: 11
- App Manager Version: Debug Build #2596
- Mode: Root

**Comment by MuntashirAkon** [comment]
MIUI? Another user has reported similar freezing issues in MIUI many months ago.

**Comment by MuntashirAkon** [comment]
Can you please take logs from the latest debug again?

**Comment by MuntashirAkon** [comment]
> But with another device, Samsung S20 FE (One UI 5.1, Android 13, No Root), the same problem is observed with exactly the same effect when running on beta-01 and debug#2723.

Logs please.

**Comment by MuntashirAkon** [comment]
Thanks.

```
07-09 00:48:16.060 I/Choreographer( 7303): Skipped 345 frames!  The application may be doing too much work on its main thread.
07-09 00:48:29.559 I/Choreographer( 7303): Skipped 808 frames!  The application may be doing too much work on its main thread.
07-09 00:48:31.610 I/Choreographer( 7303): Skipped 120 frames!  The application may be doing too much work on its main thread.
```

It appears something is causing these freezing issues while the accessibility service is running. While I'm not sure what might be causing the issues, I have some ideas. Let's see if they work.

**Comment by MuntashirAkon** [comment]
May be fixed by d475e0781958cf957b9bdafe05b31c4eb38ecb32. Can you check?

**Comment by MuntashirAkon** [comment]
Fixed by 251fd3f0eca1cbf7bdb0847b10bfd8b2d36385b4
