### ISSUE TITLE
v2.5.17-stable release plan

### ISSUE THREAD

**Issue by MuntashirAkon** [MuntashirAkon/AppManager#134]
It's been a while since the last stable release (which was v2.5.13) has published and much have been changed since. My initial plan was to make a stable release at the beginning of December but I've decided to make a stable release now as it becomes very difficult to keep the documentation up to date for both releases and pre-releases due to many substantial changes introduced of late. Besides, more translations are added now which should be very helpful to non-English speakers. Unlike the previous versions, I intend to hide testing or unimplemented (but having a placeholder) features from the release build in order to avoid confusion. Code refactor and minor issues are omitted from the plan:

**New/Amended Features**
- [x] [Locale] Add українська мова (uk) (e6f11e3)
- [x] [Scanner] Replace exodus with scanner (b345ee2)
- [x] [Scanner] Update tracker list (63d34e0)
- [x] [SysConfig] Full implementation (c908934)
- [x] [Locale] Add हिंदी (hi) (8412978)
- [x] [Installer] Display confirmation message for non-root users (70992a2)
- [x] [Locale] Add polski (Polish) (7e05af5)
- [x] [Manifest] Add more undocumented tags (7075d88)
- [x] [Locale] Add tr (Türkçe) (8e8563a)
- [x] [Installer] Offer to uninstall & install app again on signature mismatch (baac0f8 & cdf839d)
- [x] [Installer] Display changes on reinstall if signature is different (16ea03a & f6f7ac4)
- [x] [Main] Sort and filter for backups (5ab6f11)
- [x] [AppInfo] Add option to uninstall updates (98eda2a)
- [x] [Installer] Add a confirm notification for non-root (5e7bf67)
- [x] [Settings] Migrate to preferences (c0f37a7)
- [x] [RunningApps] Add sort and filters (06013b6)
- [x] [RunningApps] Add SELinux context info (94ffdd9)
- [x] [Locale] Add pt in language settings (28cafbf)
- [x] [AppInfo] Display “KeyStore” tag for apps that use Android KeyStore (1e632b2)
- [x] [App] Offer users to keep app data during the uninstall of AM (18e33c3)
- [x] [AppInfo] Display “Systemless App” for apps installed via Magisk (1dafe2b)
- [x] [AppInfo] Add a tag for apps with running services (f8f9854)
- [x] [Refactor] Save logs internally instead of just logcat (3763312)
- [x] [Installer] Pipe apk streams directly to stdin for root users (1f28064)
- [x] [Refactor] Switch to libsu (c2ed905)
- [x] [AppInfo] Add downgrade and reinstall (c3cebad)
- [x] [Installer] Add option to downgrade for root/ADB users (ae9b2ab)
- [x] [RunningApps] Add process state (d32a200)
- [x] [Installer] Recommend ABI, density and locale (6694cf4)
- [x] [Locale] Add bn and nb (d826657)
- [x] [Apk] Add apk-parser for parsing manifest files (36880af)
- [x] [Refactor] Add fast scroller for Main and Details pages (bf95736)
- [x] [Blocking] Setup guard, remove compatibility for v2.5.6 (da2183e)
- [x] [RunningApps] Add popup menu replacing action buttons (8bbcc83)
- [x] [RunningApps] Add SRL (95a4724)
- [x] [BatchOps] Add batch enable option (747c38f)
- [x] [Installer] Add split apk chooser (68a30d3)
- [x] [Locale] Add zh-CN translations (not verified) (215fa10)
- [x] [Locale] Add ru translations (05a3967)
- [x] [App] Add toybox (#87) (60f6c0e)
- [x] [Locale] Add custom language chooser (a6f311f)
- [x] [Apk] Add support for obb files (8689ed0)
- [x] [Apk] Install apk using a background service (0d65594)
- [x] [BatchOps] Add notification progress for backups (77ebae4)
- [x] [1-ClickOps] Perform operations using BatchOpsService (78f1c05)

**Fixes**
- [x] [Crypto] Fix NullPointerException while fetching OpenPGP intent services (ff5727a)
- [x] [AppInfo] Add custom focus instructions for label, pkg name and version (b4c9b57)
- [x] [AppInfo] Fix scrolling behaviour (9b9fa2d)
- [x] [AppInfo] run-as as root since Termux doesn't support ADB (44fa032)
- [x] [AppDetails] Update permissions on refresh (c9914a4)
- [x] [Usage] Fix progress indicators being not recyled (1ccf010)
- [x] [SharedPref] Fix persistence of constraints between launch (5b0d8d9)
- [x] [Manifest] Fix crash on resume if the manifest is very large (eaee64f)
- [x] [Usage] Display warning if usage access settings can't be opened (#107) (1019f41)
- [x] [AppDetails] Improve signature tab (aa2492e)
- [x] [AppInfo] Use pm uninstall for ADB users as well (b0efe5c)
- [x] [AppInfo] Fix displaying apps as running if system has any ANR service (81164d2)
- [x] [Backup] Ask storage permission on opening backup/restore dialog (31e6bad)
- [x] [Refactor] Close all input streams to prevent leaks (4782aa4)
- [x] [Rules] Apply rules based on user handle (8bd8789)
- [x] [Refactor] Custom focus mode to improve keypad navigation (#107) (87537d2)
- [x] [RunningApps] Fix wrong memory usage (bcf38cb)
- [x] [Main] Remove old am.jar on app update (4c5c3ea)
- [x] [Manifest] Use apk-parser to parse manifest of installed apps (af7de28)
- [x] [AppDetails] Give running services the higest priority (787a62d)
- [x] [AppDetails] Preserve sort order for components, app ops and permissions (eae3f7f & b63fa56)
- [x] [Apk] On demand cache of apk files (41a54f5)
- [x] [Server] Restart server on SocketTimeoutException (eddd12e)
- [x] [1-ClickOps] Rename OP_BLOCK_COMPONENTS to OP_IGNORE_APP_OPS (3809059)
- [x] [AppOps] Consider the parent of an op instead of the op itself (a295e48)
- [x] [AppInfo] Support apk sharing via bluetooth (ba3faf6)
- [x] [AppInfo] Fix apk sharing options (b7a1fdb)
- [x] Fix detecting splits if their manifest doesn't have configForSplit (fb97f2d)
- [x] [Blocking] Use single CB instance instead of multiple (dd24507)
- [x] [AppInfo] Fix parsing data usage (9eaa357)
- [x] [Main] Use getInstalledPackages to speed things up (d288c01)
- [x] [BatchOps] Fix app data not clearing in batch uninstall (a35e484)
- [x] [AppInfo] Remove shared libs from What's New (8c36f74)
- [x] [Apk] Add install support for non-root users (9a8e0ee)
- [x] [Main] Update app info properly after a batch operation (9e30f60)
- [x] [Main] Remove sort by app size in favour of target SDK (346e57f)
- [x] [AppDetails] Disable permission toggle for apps targeting API 23 or less (a6c6031)

**Features to be hidden**
- [x] Backup/restore
- [x] Profile
- [x] Unimplemented features in 1-click ops
- [x] Remove splits based on ABI (F-Droid doesn't support it)
