### ISSUE TITLE
Backup related suggestions/discussion about UI/UX and features

### ISSUE THREAD

**Issue by Cyberavater** [MuntashirAkon/AppManager#355]
N.B. This is more like a placeholder issue, which is filed upon the dev's request,(https://github.com/MuntashirAkon/AppManager/issues/347#issuecomment-812919232). The suggestions were initially proposed here, (https://github.com/MuntashirAkon/AppManager/issues/347#issue-846449180). [So, it'd be mostly copy paste]

Considerable suggestion (since given below will override existing UI/UX and function):
- [x] If the backed-up app version is lower than the installed version, "Backup" should be written in "Red" vice-versa if the backed-up app version is equal or higher, "Backup" should be written in "Green". [Also, making the text bold should look nice]. This would require another way to show the apps that are Backup up but uninstalled. One (my own) suggestion is to make them faded in the list.
- [x] "Data" should not be selected for backing up "External Data". The user could be interested in only external data but not data. Instead, add a warning in the description that it might not work and in the docs add the reason ( https://github.com/MuntashirAkon/AppManager/issues/355#issuecomment-813406900, https://github.com/MuntashirAkon/AppManager/issues/355#issuecomment-813416079) [Example case; The user doesn't want to backup the progress of a game but wants external data as he doesn't want to re-download the large external data that he already downloaded once.]
- [x] Make Backup/Restore menu options more Syntacticly Sound. For example, the option that deals with Cache should be named "Cache", selecting it would include the app's cache in the backup. This change would impact and remodel the following;
1. APK (+Split) [This would include apps apk and split-apk in backup/restore] [This would replace the current "APK only" option]
2. ODEX/VDEX [This would include apps odex and vdex in backup/restore] [This would replace the current "Source" option] [The dev can name it something else, i.e. "Regenerativies" (as it regenerates per install/updates,) and specify in the description what it includes] [This option is still questionable, as I've yet to see it's usefulness. #313]
3. "Cache" [Of course! as explained above] [This would replace the current "Exclude Cache" option]

Of course, this would re-format the current order and would put the "ODEX/VDEX" option just above the "Cache" option.

- [x] Add separate a restore menu (Reason mentioned here; https://github.com/MuntashirAkon/AppManager/issues/355#issuecomment-813396954) 
[I have two proposals to implement this restore menu :
 1. At the top user will select which backup he wants to restore and the components list will update accordingly with the conditions given below.
 2.  This restore menu will have two pages. On the first page, the user will select which backup to restore, then the second page will contain the components accordingly with the conditions given below.]
- [x] Components that are not backed up, make them un-selected and faded in the Restore menu, also remove options that don't make sense in the Restore menu, i.e. Multiple Backup? etc.
- [x] When restoring an **Uninstalled** app, APK (+Split) should be forced selected and faded (User can't unselect that). - if APK (+Split) doesn't exist for such an app, don't run the restore process instead, throw a toast that APK doesn't exist.
- [x] On the backup and restore menu, the Data component should be un-selected and faded for non-rooted users. When the user tries to select it, a toast will be thrown that This feature is for rooted users] [Ain't sure about the current state, maybe the whole Backup/Restore is unavailable for them]
- [x] On the backup delete menu, if no backup is selected and the user presses the delete backup button, don't run the operation instead, throw a toast that no backup is selected. OR, don't show the button until a backup is selected.
- [x] For backup but uninstalled apps' batch selection, don't show that list big list, since most of them are not applicable anyway, only show restore menu. [When the user selects such an app instead of throwing a toast launch restore menu?]
- [x] After restoring, if some apps that require restart will prompt the user to restart the device upon backup completion notification. (i.e. If SSID was restored).
- [x] Throw a detailed prompt when backup-related issues occur. I.e When a backup (or restore) fails the prompt should contain Both the app name and the reason why the backup failed i.e Keystore backup not enabled (possibly with an error code too so that the user can use that as a reference to look up possible solutions from the docs). This prompt should also contain a Copy-log button, that would copy the exact log of the error so that the user can easily report the error. [Outcome: Users will have better chances of understanding the [error](https://github.com/MuntashirAkon/AppManager/issues/473#issuecomment-932676636) on their own and the copy-log button would help the user to send very specific logs rather than sending unrelated logs (Which I know, I myself had done many times and annoyed the dev, sorry)].
- [x] Backup import --remove-source-during option. [This will help users to import data of all apps (let's say 20GB) while having available space only for the app with MAX space (say 2GB). The Source won't be around if something goes wrong of course!].

**Comment by MuntashirAkon** [comment]
> * make them faded and un-selectable in the Restore menu

What's a restore menu? AM doesn't have a restore menu.

**Comment by Cyberavater** [comment]
> What's a restore menu? AM doesn't have a restore menu.

Oh yeah, right. AM doesn't have a separate restore menu. At the time I added that suggestion, I was restoring an uninstalled app (so, the backup option wasn't there), AM threw an error then, upon reading the log I found that the specific component was not backed up in the first place. Assuming AM would reach an even larger user amount, I would suggest creating a separate "Restore" page to prevent these types of issues (as most users won't like these errors and probably won't even read the log). This would open room for another nice feature;

- [ ] When restoring an **Uninstalled** app, APK (+Split) should be forced selected and grayed out (User can't unselect that).

**Comment by Deerp1976** [comment]
Backing up external data is a good idea but in practice it doesn't always
work with games especially if they are online. Online games will make their
own checks and any discrepancies will end up on resulting in full downloads
again anyway.

Backing up obb data is another matter as that will stay the same if the
build version is the same but anything in android/data is risky because a
lot of games will result in full downloads.

**Comment by Cyberavater** [comment]
> Backing up external data is a good idea but in practice it doesn't always
work with games especially if they are online. Online games will make their
own checks and any discrepancies will end up on resulting in full downloads
again anyway.

Can you name an example? Mobile Legends is an online that would not make you re-download if it already exists in the expected location (An example from my side and I think/believe most games work this way.).

**Comment by Deerp1976** [comment]
Need for Speed No Limits. Civilization VI if you have the dlc will make
checks when it was originally downloaded.

Lords Mobile I think does as well. If a game keeps the game save in
android/data, there is a much bigger risk to you having to download the
entire files again.

Dominations. That has a phone permission where it checks your IMEI and then
compares the data last saved to what it has on their server. Any
discrepancy will result in full download of data.

**Comment by Cyberavater** [comment]
So, I guess that that would be on the user to figure out if backing up only external data would work or not, as there exists some app where it works, AM should not put any limit there.

**Comment by Deerp1976** [comment]
Agreed. The option should exist but perhaps with a warning that it may not
be possible to keep the data backed up or it may be overwritten once you
use the app again. Gameloft games are extremely strict when it comes to
things like this. They do not even allow you to install more than 1 game
outside of playstore. It's not worth your time backing up their data on my
of their games but as you say, that's up to the user to make that decision.
I do believe a warning should come with backing up data in android/data or
at the very least mentioned in the documentation.

What do you think?

**Comment by Cyberavater** [comment]
Yes, warning the user in description (and in detail with the above-mentioned reasons in docs) should be sufice.

**Comment by MuntashirAkon** [comment]
> Yes, warning the user in description (and in-detail with the above-mentioned reasons in docs) should be suffice.

It can be mentioned in the docs but not in the description since the **Data** flag is selected by default.

**Comment by MuntashirAkon** [comment]
@Cyberavater add checklists in the first comment only. They won't be picked up by GitHub if you do it in the other comment.

**Comment by Cyberavater** [comment]
Right, but with a short warning in the description, the user should know, generally it's a good idea to backup Data too if he was thinking about only backing up External Data (even without reading the docs).

**Comment by MuntashirAkon** [comment]
> If the backed-up app version is lower than the installed version, "Backup" should be written in "Red" vice-versa if the backed-up app version is equal or higher, "Backup" should be written in "Green". [Also, making the text bold should look nice]. This would require another way to show the apps that are Backup up but uninstalled. One (my own) suggestion is to make them faded in the list.

In order to preserve compatibility, the colour codes for “backup” will be the following:
1. `Red`: Uninstalled app (as usual)
2. `Orange`: The version code of the installed app is lower or equal to the version code of the backed up app
3. `Dark cyan`: Vice versa.

**Comment by MuntashirAkon** [comment]
Implemented in b87b2ab0, 7ba10221 and 1a83c105. The last three suggestions are the outcome of a greater problem with how the backup UI is handled and will be addressed in a separate issue.

**Comment by Cyberavater** [comment]
Making uninstalled apps faded in the list would've looked more elegant, but I guess this is not that big of an issue.
I see "APK Only" hasn't been renamed to "APK (+Splits)" or something similar in the last version shared on TG.

>The last three suggestions are the outcome of a greater problem with how the backup UI is handled and will be addressed in a separate issue.

Okay, I'll wait till you open that issue and add my further related suggestions there.

**Comment by MuntashirAkon** [comment]
> I see "APK Only" hasn't been renamed to "APK (+Splits)" or something similar in the last version shared on TG.

Ah, my mistake. Thanks for reporting.

**Comment by Cyberavater** [comment]
> The last three suggestions are the outcome of a greater problem with how the backup UI is handled and will be addressed in a separate issue.

Since I didn't fount any issues regarding it, I've updated the OP with some more suggestions and two possible ways to implement it.

**Comment by Cyberavater** [comment]
One more reason to consider not to do restore parallelly is that it fails on some condition (i.e when restoring addons)

Reproduction steps:

1.  Backup the addon apps (ex link: https://mixplorer.com/#addons)
2. Uninstall all the addons.
3. Try to batch restore all the addons, you'll fail.
- Now try to do it one by one and it'll work.

**Comment by MuntashirAkon** [comment]
> * Add separate a restore menu (Reason mentioned here; [Backup related suggestions/discussion about UI/UX and features #355 (comment)](https://github.com/MuntashirAkon/AppManager/issues/355#issuecomment-813396954))
>   [I have two proposals to implement this restore menu :
> 
>   1. At the top user will select which backup he wants to restore and the components list will update accordingly with the conditions given below.
>   2. This restore menu will have two pages. On the first page, the user will select which backup to restore, then the second page will contain the components accordingly with the conditions given below.]

I think this should be handled separately depending on how many apps are selected.

1. If only a single app is selected, both of the suggestions are correct.
2. If multiple apps are selected, we only restore the _base_ backups, so we can directly update backup options.

But in both cases, we do not need a separate menu for restoring a backup. Instead, we could add two tabs: one for backup (assuming, users need to use backup a lot more than the restore and the selected apps are actually installed) and the other for restore.
