### ISSUE TITLE
Add Intent Intercept like features

### ISSUE THREAD

**Issue by MuntashirAkon** [MuntashirAkon/AppManager#75]
[Intent Intercept](https://github.com/k3b/intent-intercept) allows user to edit the content of intercepted intent before resending it to the destination apps. This is useful not only for debugging purpose but also for other purposes.

## Roadmap
Unlike the original app, my intention is to make it as smooth as possible. This includes all the features of Intent Intercept along with the following extras:
1. [ ] Save mime-specific default apps (via an always button)
2. [x] Add/remove extras (only for known classes)
3. [x] Add/remove flags
4. [x] Add/remove categories
5. [x] Set identifier
6. [x] Set component name
7. [x] Set package name
5. [x] Extended support for exported activities in the activities tab
6. [ ] Save/import/export intents
7. [x] For root users, open non-exported activities via root (for activities tab)
8. [x] Set data and type
9. [ ] Support for receivers and services

**Comment by bb010g** [comment]
Noting that only `get*Extra` values are handled currently, while `get*ArrayListExtra` values are ignored.

**Comment by MuntashirAkon** [comment]
> Noting that only `get*Extra` values are handled currently, while `get*ArrayListExtra` values are ignored.

Thanks for reporting, I'll look into it.

**Comment by MuntashirAkon** [comment]
> Noting that only `get*Extra` values are handled currently, while `get*ArrayListExtra` values are ignored.

Can you provide the steps to reproduce this? They seem to be working fine on my end.

**Comment by isral** [comment]
Is it possible to disable this?
It's hijacking all non associated file type in file manager, pretty annoying.

**Comment by MuntashirAkon** [comment]
> Is it possible to disable this?

Yes. Read the [relevant docs](https://muntashirakon.github.io/AppManager/en/#subsubsec:enable/disable-features).

**Comment by Bakr-Ali** [comment]
Is it possible to intercept an intent that has specified its target package?

Like this intent:
![Screenshot_20241013125424](https://github.com/user-attachments/assets/f72d7862-84bb-4114-8e97-ac5acd897e05)

When leaving the package field empty, it can be opened/intercepted by several apps including AM. But when I specified the package as `com.android.chrome`, only Chrome appears in the matching activities.

If not possible in AM, then can you please tell me if it is possible at all? Using ADB? I'm trying to intercept similar intents to the one I attached above (from the now unsupported [Sesame Search](https://play.google.com/store/apps/details?id=ninja.sesame.app.edge)) to learn how they work and use them in [Kvaesitso](https://github.com/MM2-0/Kvaesitso).

**Comment by MuntashirAkon** [comment]
> Is it possible to intercept an intent that has specified its target package?

It's only possible via root (e.g. *Posed apps or Frida). Had it been possible in no-root mode, that would've been a disaster in terms of security.

**Comment by Bakr-Ali** [comment]
> Had it been possible in no-root mode, that would've been a disaster in terms of security.

Yeah, that's what I thought too but I asked anyway to make sure.
Thanks for the quick response.

**Comment by whitedavidp** [comment]
After finding the Intent Intercept app not working on my A12 device, I found the mechanism here. Thanks so much for including it. Wow!
